- name: Include user tasks
  include: users.yml
  tags:
    - apache

- name: Include installers tasks
  include: install.yml
  tags:
  - apache

- name: Include clean default installation
  include: clean-defaults.yml

- name: Include configuration tasks
  include: configure-2.2.yml